apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  hub: docker.io/hochacha
  tag: tls12_1.22.3
  meshConfig:
    tlsDefaults:
      cipherSuites:
        - ECDHE-ECDSA-CHACHA20-POLY1305

