apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  hub: docker.io/${HUB}
  tag: ${TAG}
  meshConfig:
    meshMTLS:
      cipherSuites:
      - ECDHE-RSA-AES256-GCM-SHA384 
