apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  hub: docker.io/hochacha
  tag: tls12_1.22.3
  meshConfig:
    meshMTLS:
      cipherSuites:
        - ECDHE-RSA-AES128-GCM-SHA256
