apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  hub: docker.io/hochacha
  tag: 240806_Q1_AES256_to_AES128_v1
  meshConfig:
    meshMTLS:
      cipherSuites:
        - ECDHE-PSK-AES256-CBC-SHA
